### ISSUE TITLE
Write documentation

### ISSUE THREAD

**Issue by DaazKu** [vanilla/vanilla-docker#9]
Write documentation.

- [ ] Explain how things work.
    - [ ] How everything is wired together.
    - [x] What are the different images and what they do.
    - [ ] The configuration structure.
- [x] Create documentation on how to integrate docker in PHPStorm.

**Comment by Charrondev** [comment]
Might be good to also add:

- [ ] How to do the setup on Mac & Windows.

As is are actually setup guide for Vanilla on localhost is kind of anemic and it's a big obstacle that results in some VIP clients constantly pushing changes to staging with Theme Pull instead of developing locally.

Could go [here](https://docs.vanillaforums.com/developer/installation/) and be linked from this repo and the primary Vanilla repo.

If you have a busy sprint I can could also do it if my setup goes well.

**Comment by DaazKu** [comment]
This is a bit premature. Everything is set to work for mac as of now.
We still need to add more services (memcached for example) and trying to support windows is out of scope right now. I would suggest creating an issue about it.

The self signed certificate and the "loopback" hack might be a problem for windows. Less so for linux.
